library managment system/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace library_managment_system.Models
{
    public class Book
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Image { get; set; }

        [Required]
        public int TotalCopies { get; set; }

        public int  AvailableCopies { get; set; }
    }
}

library managment system/Models/Borrow.cs
using System.ComponentModel.DataAnnotations;

namespace library_managment_system.Models
{
    public class Borrow
    {
        public int Id { get; set; }

        [Required]
        public int BookId { get; set; }

        [Required]
        public int PersonId { get; set; }

        public DateTime BorrowDate { get; set; } = DateTime.Now;

        public DateTime? ReturnDate { get; set; }
    }
}

library managment system/Models/Context.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace library_managment_system.Models
{
    public class Context :DbContext
    {
        public Context() : base()
        { }
        public Context(DbContextOptions<Context> options) : base(options)
        {

        }
        public DbSet<Book> Books { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Borrow> Borrows { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseSqlServer("Data Source=.;Initial Catalog=LibraryDb;Integrated Security=True;Encrypt=False");
            
        }
    }
}

library managment system/Models/ErrorViewModel.cs
namespace library_managment_system.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

library managment system/Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace library_managment_system.Models
{
    public class Person
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Code { get; set; }
    }
}

library managment system/Controllers/BookController.cs
using library_managment_system.Models;
using library_managment_system.Repository;
using Microsoft.AspNetCore.Mvc;

namespace library_managment_system.Controllers
{
    public class BookController : Controller
    {
        IPersonRepo _PersonRepo;
        IBookRepo _BookRepo;
        IBorrow _Borrow;
        public BookController(IPersonRepo PersonRepo ,IBookRepo BookRepo , IBorrow iborrow)
        {
            _PersonRepo = PersonRepo;
            _BookRepo = BookRepo;
            _Borrow = iborrow;
        }

        // GET: Book/AllBooks
        [HttpGet]
        public ActionResult AllBooks()
        {
            var books = _BookRepo.GetAll(); // Assuming you have a method to get all books in your repository
            return View(books);
        }

        // GET: Book/AddBook
        [HttpGet]
        public ActionResult AddBook()
        {
            var imagesPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images");
            ViewBag.Images = Directory.GetFiles(imagesPath).Select(Path.GetFileName).ToList();
            return View();
        }


        // POST: Book/AddBook
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveBook(Book model)
        {
            // Ensure the model is valid and the book name is provided
            if (ModelState.IsValid && !string.IsNullOrEmpty(model.Name))
            {
                // Construct the image path based on the selected image filename
                var imagesDirectory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images");
                var imagePath = Path.Combine(imagesDirectory, model.Image);

                // Check if the image file exists in the specified path
                if (System.IO.File.Exists(imagePath))
                {
                    // Create a new book object with the provided details
                    Book book = new Book
                    {
                        Name = model.Name,
                        Image = model.Image, // Use the provided image name from the model
                        TotalCopies = model.TotalCopies,
                        AvailableCopies = model.TotalCopies // Initialize AvailableCopies to match TotalCopies
                    };

                    // Insert the new book into the repository
                    _BookRepo.Insert(book);

                    // Redirect to the Home index page upon successful insertion
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    // Image file does not exist, return to the view with an error message
                    ModelState.AddModelError("Image", "The selected image does not exist.");
                }
            }

            // If model validation fails or image doesn't exist, reload the image list for the dropdown
            var imagesPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images");
            ViewBag.Images = Directory.GetFiles(imagesPath).Select(Path.GetFileName).ToList();

            // Return to the AddBook view with the current model
            return View("AddBook", model);
        }



        // GET: Book/BorrowBook
        [HttpGet]
            public ActionResult BorrowBook()
        {
            return View();
        }

        // POST: Book/BorrowBook
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BorrowBook(string code, string bookName)
        {
            try
            {
                _Borrow.BorrowBook(code, bookName);
                return RedirectToAction("Index", "Home");
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        public ActionResult ReturnBook()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ReturnBook(string code, string bookName)
        {
            try
            {
                _Borrow.ReturnBook(code, bookName);
                return RedirectToAction("Index", "Home");
            }
            catch (InvalidOperationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

library managment system/Controllers/HomeController.cs
using library_managment_system.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace library_managment_system.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

library managment system/Controllers/PersonController.cs
using library_managment_system.Models;
using library_managment_system.Repository;
using Microsoft.AspNetCore.Mvc;

namespace library_managment_system.Controllers
{
    public class PersonController : Controller
    {
        IPersonRepo _PersonRepo;
        public PersonController(IPersonRepo PersonRepo)
        {
            _PersonRepo = PersonRepo;
        }
        // GET: Person/AddPerson
        public ActionResult AddPerson()
        {
            return View();
        }

        // POST: Person/AddPerson
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPerson(Person model)
        {
            if (ModelState.IsValid)
            {
                _PersonRepo.Insert(model);

                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }
    }
}

library managment system/Views/Book/AddBook.cshtml
@model library_managment_system.Models.Book

@{
    ViewBag.Title = "Add Book";
}

<h2></h2>
<div class="main-banner" id="top">
<div class="contact-us section" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-6  align-self-center">
                <div class="section-heading">
                    <h6>Add Book</h6>
                    <p>Thank you for choosing our Linbrary</p>
                    <div class="special-offer">
                        <span class="offer">off<br><em>50%</em></span>
                        <h6>Valide: <em>24 April 2036</em></h6>
                        <h4>Special Offer <em>50%</em> OFF!</h4>
                        <a href="#"><i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-us-content">
                    <form id="contact-form" asp-action="SaveBook" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Name)
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Image)
                                        <select name="Image" class="form-control">
                                            <option value="">-- Select an Image --</option>
                                            @if (ViewBag.Images != null)
                                            {
                                                foreach (var image in ViewBag.Images as List<string>)
                                                {
                                                    <option value="@image">@image</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TotalCopies)
                                        @Html.TextBoxFor(model => model.TotalCopies, new { @class = "form-control" })
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="orange-button">Add New Book</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@* 
<form asp-action="SaveBook" method="post">
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image)
        <select name="Image" class="form-control">
            <option value="">-- Select an Image --</option>
            @if (ViewBag.Images != null)
            {
                foreach (var image in ViewBag.Images as List<string>)
                {
                    <option value="@image">@image</option>
                }
            }
        </select>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.TotalCopies)
        @Html.TextBoxFor(model => model.TotalCopies, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Add Book</button>
</form>
 *@

library managment system/Views/Book/AllBooks.cshtml
@model IEnumerable<library_managment_system.Models.Book>

@{
    ViewData["Title"] = "All Books";
}
<div class="main-banner" id="top">
<section class="section courses" id="courses">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-heading">
                    <h6>Library Management System</h6>
                    <h2>Available Books</h2>
                </div>
            </div>
        </div>
        <div class="row event_box">
            @foreach (var book in Model)
            {
                <div class="col-lg-4 col-md-6 align-self-center mb-30 event_outer col-md-6">
                    <div class="events_item">
                        <div class="thumb">
                            <a href="#"><img src="~/Images/@book.Image" alt="@book.Name" style="width:100%; height:450px; object-fit:cover;" /></a>
                            <span class="category">Available Copies: @book.AvailableCopies</span>
                        </div>
                        <div class="down-content">
                            <h4>@book.Name</h4>
                            <h4>
                                <span class="price"><span style="font-size: 14px;">Total: @book.TotalCopies</span></span>
                            </h4>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<div></div>

library managment system/Views/Book/BorrowBook.cshtml
@{
    ViewBag.Title = "Borrow Book";
}

<h2></h2>
<div class="main-banner" id="top">
<div class="contact-us section" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-6  align-self-center">
                <div class="section-heading">
                    <h6>Borrow Book</h6>
                    <p>Borrowing Period from week to 15 days</p>
                    <div class="special-offer">
                        <span class="offer">off<br><em>50%</em></span>
                        <h6>Valide: <em>24 April 2036</em></h6>
                        <h4>Special Offer <em>50%</em> OFF!</h4>
                        <a href="#"><i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-us-content">
                    <form id="contact-form" asp-action="BorrowBook" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        <label>Person Code</label>
                                        <input type="text" class="form-control" name="code" />
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        <label>Book Name</label>
                                        <input type="text" class="form-control" name="bookName" />
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="orange-button">Borrow Book</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

@if (ViewData.ModelState.ContainsKey(""))
{
    <div class="alert alert-danger">
        @ViewData.ModelState[""].Errors[0].ErrorMessage
    </div>
}

library managment system/Views/Book/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

library managment system/Views/Book/ReturnBook.cshtml
@{
    ViewBag.Title = "Return Book";
}

<h2></h2>
<div class="main-banner" id="top">
<div class="contact-us section" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-6  align-self-center">
                <div class="section-heading">
                    <h6>Borrow Book</h6>
                    <p>Borrowing Period from week to 15 days</p>
                    <div class="special-offer">
                        <span class="offer">off<br><em>50%</em></span>
                        <h6>Valide: <em>24 April 2036</em></h6>
                        <h4>Special Offer <em>50%</em> OFF!</h4>
                        <a href="#"><i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-us-content">
                    <form id="contact-form" asp-action="ReturnBook" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        <label>Person Code</label>
                                        <input type="text" class="form-control" name="code" />
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        <label>Book Name</label>
                                        <input type="text" class="form-control" name="bookName" />
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="orange-button">Return Book</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

@if (ViewData.ModelState.ContainsKey(""))
{
    <div class="alert alert-danger">
        @ViewData.ModelState[""].Errors[0].ErrorMessage
    </div>
}

library managment system/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- ***** Header Area End ***** -->

<div class="main-banner" id="top">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="owl-carousel owl-banner">
                    <div class="item item-1">
                        <div class="header-text">
                            <span class="category">Our Books</span>
                            <h2>Explore Our Vast Collection of Books</h2>
                            <p>Discover a wide variety of books in our library, carefully curated to cater to all your reading needs. Whether you're looking for academic resources or leisure reading, we have something for everyone.</p>
                            <div class="buttons">
                                <div class="main-button">
                                    <a href="#">Browse Collection</a>
                                </div>
                                <div class="icon-button">
                                    <a href="#"><i class="fa fa-play"></i> Learn More About Us</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item item-2">
                        <div class="header-text">
                            <span class="category">Quality and Variety</span>
                            <h2>Get the Best Books Across All Genres</h2>
                            <p>Our library offers a diverse selection of books across various genres and disciplines. From the latest bestsellers to timeless classics, you'll find books that inspire, educate, and entertain.</p>
                            <div class="buttons">
                                <div class="main-button">
                                    <a href="#">Start Reading</a>
                                </div>
                                <div class="icon-button">
                                    <a href="#"><i class="fa fa-play"></i> See Our Top Picks</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item item-3">
                        <div class="header-text">
                            <span class="category">Online Learning</span>
                            <h2>Online Learning helps you save the time</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temporious incididunt ut labore et dolore magna aliqua suspendisse.</p>
                            <div class="buttons">
                                <div class="main-button">
                                    <a href="#">Request Demo</a>
                                </div>
                                <div class="icon-button">
                                    <a href="#"><i class="fa fa-play"></i> What's Online Course?</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

library managment system/Views/Person/AddPerson.cshtml
@model library_managment_system.Models.Person

@{
    ViewBag.Title = "Add Person";
}

<h2></h2>
<div class="main-banner" id="top">
<div class="contact-us section" id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-6  align-self-center">
                <div class="section-heading">
                    <h6>Add Person</h6>
                    <p>Welcome and Thank you for choosing our Library</p>
                    <div class="special-offer">
                        
                        <a href="#"><i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="contact-us-content">
                    <form id="contact-form" asp-action="AddPerson" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Name)
                                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Code)
                                        @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                                    </div>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="orange-button">Add New Person</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

library managment system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Scholar - Online School HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/css/fontawesome.css">
    <link rel="stylesheet" href="~/css/templatemo-scholar.css">
    <link rel="stylesheet" href="~/css/owl.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<!--

TemplateMo 586 Scholar

https://templatemo.com/tm-586-scholar

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
 
  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                        <a asp-controller="Home" asp-action="Index" class="logo">
                        <h1>Library</h1>
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Serach Start ***** -->
                    <div class="search-input">
                      <form id="search" action="#">
                        <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                        <i class="fa fa-search"></i>
                      </form>
                    </div>
                    <!-- ***** Serach Start ***** -->
                    <!-- ***** Menu Start ***** -->
                        <ul class="nav" style="color: darkgray;">
                            <li class="scroll-to-section"><a asp-controller="Book" asp-action="AllBooks" class="active">Our Library</a></li>
                            <li class="scroll-to-section"><a asp-controller="Book" asp-action="BorrowBook"> Borrow Book</a></li>
                            <li class="scroll-to-section"><a asp-controller="Book" asp-action="ReturnBook">Return Book</a></li>
                            <li class="scroll-to-section"><a asp-controller="Book" asp-action="AddBook">Add Book</a></li>
                            <li class="scroll-to-section"><a asp-controller="Person" asp-action="AddPerson">Add Person</a></li>
                        </ul>

                        <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  
  @RenderBody()

   
  
  
  <footer>
    <div class="container">
      <div class="col-lg-12">
        <p>Copyright © 2036 library . All rights reserved. &nbsp;&nbsp;&nbsp; Design: <a  rel="nofollow" target="_blank"></a></p>
      </div>
    </div>
  </footer>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="~/lib/jquery/dist/jquery.js"></script>
  <script src="~/lib/bootstrap/dist/css/bootstrap.min.js"></script>
  <script src="~/js/isotope.min.js"></script>
  <script src="~/js/owl-carousel.js"></script>
  <script src="~/js/counter.js"></script>
  <script src="~/js/custom.js"></script>

  </body>
</html>